### ISSUE TITLE
cciss device like c1d[1-9]

### ISSUE THREAD

**Issue by Mvairs** [IvanBayan/Zabbix-RAID-cciss#1]
Device like c1d1 c1d2 does not finding.

push( @controllers, "/dev/cciss/$dev" ) if( $dev =~ /^c\d+d0/ );
replace 
push( @controllers, "/dev/cciss/$dev" ) if( $dev =~ /^c\d+d*/ );

**Comment by IvanBayan** [comment]
Hi.
According to manual only /dev/cciss/c*d0 must be queried.

> DEVICE
>        The DEVICE argument indicates which RAID controller is to  be  queried.
>        Note, that it indicates which RAID controller, not which logical drive.
>       For the cciss driver, the "d0" nodes matching "/dev/cciss/c*d0" are the
>        nodes which correspond to the RAID controllers.  (See note  1,  below.)
>        It  is  not  necessary to invoke cciss_vol_status on each logical drive
>        individually, though if you do this, each time it will report the  sta‐
>        tus of ALL logical drives on the controller.
